services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest@sha256:3400c429c5f9e1b21d62130fb93b16e2e772d4fb7695bd52fc2b743800b9fe9e
    container_name: aura-docker-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      SERVICES: 0
      TASKS: 0
      POST: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - aura-proxy

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine@sha256:24faf1015b45a026b205a1961ef2e4b0ea15a593dc05e89b7911eec2ccb1c3e8
    container_name: aura-caddy
    restart: unless-stopped
    ports:
      # Use custom loopback address 127.0.0.2
      - "127.0.0.2:80:80"
      - "127.0.0.2:443:443"
      - "127.0.0.2:443:443/udp" # HTTP/3
    volumes:
      - ./certs:/certs:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - aura-proxy
    environment:
      - CADDY_INGRESS_NETWORKS=aura-proxy
      - CADDY_DOCKER_ENDPOINT=tcp://docker-socket-proxy:2375
    depends_on:
      - docker-socket-proxy
    labels:
      caddy: ""

  whoami:
    image: traefik/whoami:latest@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    container_name: aura-whoami
    restart: unless-stopped
    networks:
      - aura-proxy
    environment:
      - WHOAMI_PORT_NUMBER=80
      - WHOAMI_NAME=Aura-WhoAmI
    labels:
      caddy: whoami.aura
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "/certs/domains/whoami/cert.pem /certs/domains/whoami/key.pem"
      caddy.header.X-Served-By: "Aura Proxy"
      caddy.encode: gzip

  coredns:
    image: coredns/coredns:latest@sha256:9b9128672209474da07c91439bf15ed704ae05ad918dd6454e5b6ae14e35fee6
    container_name: aura-coredns
    restart: unless-stopped
    command: -conf /config/Corefile
    ports:
      # Bind DNS server to custom loopback address 127.0.0.2
      - "127.0.0.2:53:53/udp"
      - "127.0.0.2:53:53/tcp"
    volumes:
      - ./coredns:/config:ro
    networks:
      - aura-proxy

volumes:
  caddy_data:
    name: aura_caddy_data
  caddy_config:
    name: aura_caddy_config

networks:
  aura-proxy:
    name: aura-proxy
    driver: bridge